### ISSUE TITLE
How to inpainting a mesh with holes?

### ISSUE THREAD

**Issue by labwangcx** [dcoeurjo/MS-AT-MeshProcessing#1]
Hi,
Sorry to disturb you. Now I have compiled this project to denoise a noisy mesh. For a mesh with holes, how to inpaiting it with this code? I am very pleased to hear from you. Thank you

**Comment by dcoeurjo** [comment]
First, you would need to fill up the holes using a standard approach (cgal or meshlab), then the AT functional can post process this mesh to enhance the vertex positions on the filled up regions. 

The code in this repo only contains the second step of this process.

**Comment by dcoeurjo** [comment]
When using a external hole filling tool, new vertices must be colored using a green color (cf the program options)
